### Gets all currencies
GET http://localhost:3001/api/currencies/

### Gets currency with id:2
GET http://localhost:3001/api/currencies/2

### Post request with unknown endpoint
POST http://localhost:3001/api/currenc
Content-Type: application/json

    {
      "currencyCode": "PKR",
      "country":"Pakistan",
      "conversionRate": 206.74
    }


### Post request with content sent
POST http://localhost:3001/api/currencies
Content-Type: application/json

    {
      "currencyCode": "PKR",
      "country":"Pakistan",
      "conversionRate": 206.74
    }

### Post request with content missing -> "country"
POST http://localhost:3001/api/currencies
Content-Type: application/json

    {
      "currencyCode": "EUR",
      "conversionRate": 0.68
    }


### Get request with unknown endpoint
GET http://localhost:3001/api/currenc

### Put request to update "conversionRate" of id:2 to 0.8
PUT  http://localhost:3001/api/currencies/2/0.8

### Delete request of id:2
DELETE  http://localhost:3001/api/currencies/2