### Gets all currencies
GET http://localhost:3007/api/currencies/

### Gets the currency code from the currency model 
### and the country name from the country model
GET http://localhost:3007/api/currencyCountryName/

### Gets currency with id:2
GET http://localhost:3007/api/currencies/656

###
POST http://localhost:3007/api/currencies
Content-Type: application/json

    {
      "currencyCode": "USD",
      "countryId":2,
      "conversionRate": 120.2
    }

###
POST http://localhost:3007/api/currency
Content-Type: application/json

    {
      "currencyCode": "EUR",
      
      "conversionRate": 125.6
    }

###
POST http://localhost:3007/api/currency
Content-Type: application/json

    {
      "currencyCode": "EUR",
      "countryId":,
      "conversionRate": 125.6
    }

###
POST http://localhost:3007/api/currency
Content-Type: application/json

{
  "currencyCode": "PKR",
  "countryId":5231,
  "conversionRate": 206.74
}
### Post request with content sent
POST http://localhost:3007/api/currencies
Content-Type: application/json

    {
      "currencyCode": "IQD",
      "conversionRate": 976.77
    }
###
POST http://localhost:3007/api/currencies
Content-Type: application/json

    {
      "currencyCode": "EURO",
      "countryId":145,
      "conversionRate": 0.69
    }


###
POST http://localhost:3007/api/countries
Content-Type: application/json

    {
      "name": "Mexico"

    }

###
POST http://localhost:3007/api/countries
Content-Type: application/json

{
  "name": "France"

}

###
POST http://localhost:3007/api/countries
Content-Type: application/json

{
  "name": "Turkey"

}

###
POST http://localhost:3007/api/countries
Content-Type: application/json

    {
      "name": "Germany"

    }

###
POST http://localhost:3007/api/countries
Content-Type: application/json

    {
      "name": "France"

    }
### Post request with content missing -> "country"
POST http://localhost:3007/api/currencies
Content-Type: application/json

    {
      "currencyCode": "EUR",
      "conversionRate": 0.68
    }


### Get request with unknown endpoint
GET http://localhost:3007/api/currenc

### Put request to update "conversionRate" of id:2 to 0.87/api/currencies/2/0.8

### Delete request of id:2
DELETE  http://localhost:3007/api/currencies/2