name: miniproject_deployment_pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: deployment_job
    runs-on: ubuntu-latest

    steps:
      - name: checking-out code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2 
      - name: installing dependencies server
        working-directory: ./server
        run: npm install
      - name: run backend tests
        env:
            PORT: 3007 
            DB_URL: postgres://samina:JgIhH6MTVZVwwaMMpGPy16KJehiN5Yyu@dpg-cmnea1v109ks739ep0d0-a.oregon-postgres.render.com/dbname_f6sq
            DB_HOST: dpg-cmnea1v109ks739ep0d0-a.oregon-postgres.render.com
            DB_PORT: 5432
            DB_NAME: dbname_f6sq
            DB_USER: samina
            DB_PASSWORD: JgIhH6MTVZVwwaMMpGPy16KJehiN5Yyu
        working-directory: ./server
        run: npm run testServer
      - name: run frontend test
        working-directory: ./client
        run:  npm run test
